#!/bin/bash
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=${JAVA_HOME}/bin:$PATH

${OPENSHIFT_DATA_DIR}apache-maven-3.3.9/bin/mvn -f ${OPENSHIFT_REPO_DIR}pom.xml clean package -s ${OPENSHIFT_REPO_DIR}.openshift/settings.xml
cd ${OPENSHIFT_DATA_DIR}/apache-tomcat-8.5.9/bin
./startup.sh